CREATE TABLE CHUCVU(
	MACV NVARCHAR(4) NOT NULL PRIMARY KEY,
	TENCV NVARCHAR(30),
	HSPHUCAP decimal(4,2),
);

CREATE TABLE NHANVIEN(
	MANV NVARCHAR(5) NOT NULL PRIMARY KEY,
	HOLOT NVARCHAR(30),
	TEN NVARCHAR(10),
	PHAI NVARCHAR(3),
	NGAYSINH DATE,
	MACV NVARCHAR(4),
	HSLUONG decimal(4,2),
	FOREIGN KEY (MACV) REFERENCES CHUCVU(MACV),
);
	
CREATE TABLE QUATRINHLUONG (
    MANV NVARCHAR(5) NOT NULL,
    NGAYBD DATE NOT NULL,
    HSLUONG decimal(4,2),
    GHICHU NVARCHAR(50),
    PRIMARY KEY (MANV, NGAYBD),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);


INSERT INTO CHUCVU VALUES ('KT','Kế Toán',0.25)
INSERT INTO CHUCVU VALUES ('NV','Nhân Viên',0.30)
INSERT INTO CHUCVU VALUES ('PP','Phó Trưởng Phòng',0.45)
INSERT INTO CHUCVU VALUES ('TP','Trưởng Phòng',0.50)
INSERT INTO CHUCVU VALUES ('TX','Lái Xe Cơ Quan',0.25)

SELECT * FROM CHUCVU

INSERT INTO NHANVIEN VALUES ('NV001','Nguyễn Phước Minh','Tân','Nam','19-04-1975','TP',5.42)
INSERT INTO NHANVIEN VALUES ('NV002','Hà Thị Thanh','Nhàn','Nữ','09-03-1964','PP',4.74)
INSERT INTO NHANVIEN VALUES ('NV003','Văn Kiến','Anh','Nam','15-02-1960','NV',3.00)
INSERT INTO NHANVIEN VALUES ('NV004','Lý Văn','Sang','Nam','21-12-1970','NV',3.33)
INSERT INTO NHANVIEN VALUES ('NV005','Nguyễn Thị Thu','An','Nữ','22-08-1981','PP',5.08)
INSERT INTO NHANVIEN VALUES ('NV006','Nguyễn Thanh','Tùng','Nam','07-07-1977','TX',2.59)
INSERT INTO NHANVIEN VALUES ('NV007','Trần Văn','Sơn','Nam','08-07-1979','NV',2.67)
INSERT INTO NHANVIEN VALUES ('NV008','Cao Thị Ngọc','Nhung','Nữ','19-06-1980','KT',2.86)
INSERT INTO NHANVIEN VALUES ('NV009','Lê Thành','Sơn','Nam','05-12-1984','NV',2.67)
INSERT INTO NHANVIEN VALUES ('NV010','Phan Thị Thủy','Tiên','Nữ','25-10-1987','KT',2.06)

SELECT * FROM NHANVIEN

--1A
SELECT * FROM NHANVIEN WHERE MACV = 'PP'
--1B
SELECT * FROM NHANVIEN WHERE HSLUONG > 2.34 AND PHAI = 'Nữ' 
--1C
SELECT MANV, HOLOT, TEN, PHAI, NGAYSINH, DATEDIFF(YEAR, NGAYSINH, GETDATE()) AS TUOI FROM NHANVIEN;
--1D
SELECT PHAI, COUNT(*) AS TONG_SO_NHAN_VIEN FROM NHANVIEN GROUP BY PHAI;

--1E


